amadeus/mixins/parser.py
amadeus/version.py
specs/mixins/parser_spec.py

Fix UTF-8 issue and bump version

---

README.rst
amadeus/version.py

Bump version 1.0.0b8

---

amadeus/__init__.py
amadeus/client/direction.py
amadeus/travel/analytics/air_traffic/_busiest_period.py

Add direction options for the busiest travel period endpoint:
ARRIVING
DEPARTING

Add direction busiest period

---

README.rst

I found and fixed an error/typo in the documentation section of the README.  
As seen in the updated file, the sample code now functions when tested.

fix README.rst

---

README.rst

Replaced client_id and client_secret by API_KEY and API_SECRET
Fixed typos and updated examples to be aligned with our portal + other SDKs

Update authentication documentation and examples

---

README.rst
amadeus/namespaces/_shopping.py
amadeus/shopping/__init__.py
amadeus/shopping/_flight_offers_search.py
docs/index.rst
specs/namespaces/namespaces_spec.py

Fixes https://github.com/amadeus4dev/amadeus-python/issues/38

Adds support for Flight Offers Search

---

README.rst
amadeus/shopping/_flight_offers.py
amadeus/shopping/flight_offers/__init__.py
amadeus/shopping/flight_offers/_pricing.py
docs/index.rst
specs/namespaces/namespaces_spec.py

Adds support for Flight Offers Price

---

README.rst
amadeus/airport/predictions/_on_time.py
amadeus/shopping/_flight_offers.py
amadeus/shopping/flight_offers/_prediction.py
amadeus/travel/predictions/_flight_delay.py

- Update README with valid data
- Update docstrings in classes

Update docs with valid data

---

amadeus/shopping/flight_offers/_pricing.py
specs/namespaces/namespaces_spec.py
specs/namespaces/trip_parser_test.eml

- Remove unused logic in pricing
- Update tests for `Create Orders`, `Flight Offers Price`, `Hotel Booking` when input given as list
- Test `Trip Parser` when given `file and base64`
- Coverage 99%

Update tests and remove unused code from Flight Offers Pricing

---

README.rst
amadeus/booking/_flight_order.py
amadeus/client/request.py
amadeus/mixins/http.py
docs/index.rst
examples/flight_create_orders/flight_create_orders.py
specs/mixins/http_spec.py
specs/namespaces/namespaces_spec.py

Delete - Flight Order Management

---

README.rst
amadeus/reference_data/_locations.py
amadeus/reference_data/locations/_point_of_interest.py
docs/index.rst
examples/points_of_interest/points_of_interest.py
specs/namespaces/namespaces_spec.py

Add support for Retrieve functionality of POIS

---

README.rst

Minor README edits
- Build status symbols
- Code snippets

README FIX

---

amadeus/shopping/_flight_offers_search.py

Fixes https://github.com/amadeus4dev/amadeus-python/issues/89

Fix parameter names

---

.travis.yml
README.rst
amadeus/client/request.py
amadeus/mixins/http.py
amadeus/mixins/parser.py
amadeus/mixins/validator.py
amadeus/shopping/flight_offers/_pricing.py
setup.py
specs/client/request_spec.py
specs/mixins/http_spec.py
specs/mixins/parser_spec.py
tox.ini

Add support for handling 204 responses

---

amadeus/client/request.py
specs/client/request_spec.py

Fixes #
- added HTTP override, but didn't manage to test due to an environmental issue in my local machine. didn't update README or upgrade versioning either.
Remove this if you have done all of these:
* Ensure all tests pass and linting
* Add any changes to the README
* Add any changes or new comments to SDK methods
* Ensure this PR only changes what it is intended to change

added HTTP override

---

amadeus/client/location.py
amadeus/reference_data/_locations.py
amadeus/reference_data/locations/_airports.py

Fixes #
fixed typos with Airport and City search

Typo airport and city

---

README.rst
amadeus/airline/__init__.py
amadeus/airline/_destinations.py
amadeus/namespaces/_airline.py
amadeus/namespaces/core.py
docs/index.rst
specs/namespaces/namespaces_spec.py

Fixes #159
* Added support for [Airport Routes API](https://developers.amadeus.com/self-service/category/air/api-doc/airline-routes)
* Added relevant tests and docs

Add Support of Airline Routes V1.0

---

README.rst

I forgot to update the README for Trip Parser API :)

Update readme trip parser

---

README.rst
amadeus/duty_of_care/_diseases.py
amadeus/duty_of_care/diseases/__init__.py
amadeus/duty_of_care/diseases/_covid19_report.py
docs/index.rst
specs/namespaces/namespaces_spec.py

Fixes #164
- Added support for [Travel Restrictions v2 API ](https://developers.amadeus.com/self-service/category/covid-19-and-travel-safety/api-doc/travel-restrictions/api-reference)
- Added tests and docs

Add support of Travel Restrictions V2

---

.github/workflows/build.yml
sonar-project.properties

add sonar cloud actions

---

amadeus/mixins/pagination.py
specs/mixins/pagination_spec.py

Pagination was not properly working because the code assumed the page offset in the URL was always the last which is not the case. Changed to extract exact the code page offset from the URL.

Fix pagination

---

amadeus/booking/_flight_orders.py
amadeus/booking/_hotel_bookings.py
amadeus/client/request.py
amadeus/shopping/flight_offers/_pricing.py

Replace type with isinstance

---

amadeus/mixins/http.py

Update default value in post method

---

amadeus/client/errors.py
amadeus/mixins/pagination.py
amadeus/mixins/parser.py
amadeus/mixins/validator.py
amadeus/namespaces/_travel.py

Update methods that do not use their bound instance

---

README.rst
amadeus/namespaces/_ordering.py
amadeus/namespaces/_shopping.py
amadeus/namespaces/core.py
amadeus/ordering/__init__.py
amadeus/ordering/_transfer_order.py
amadeus/ordering/_transfer_orders.py
amadeus/ordering/transfer_orders/__init__.py
amadeus/ordering/transfer_orders/_transfers.py
amadeus/ordering/transfer_orders/transfers/__init__.py
amadeus/ordering/transfer_orders/transfers/_cancellation.py
amadeus/shopping/__init__.py
amadeus/shopping/_transfer_offers_search.py
docs/index.rst
specs/namespaces/test_namespaces.py

Fixes #189
1. Added Support for [Transfer Search API](https://developers.amadeus.com/self-service/category/cars-and-transfers/api-doc/transfer-search/api-reference).
2. Added Support for [Transfer Booking API](https://developers.amadeus.com/self-service/category/cars-and-transfers/api-doc/transfer-booking/api-reference).
3. Added Support for [Transfer Management API](https://developers.amadeus.com/self-service/category/cars-and-transfers/api-doc/transfer-management/api-reference).
4. Added relevant comments and tests.

Support for Cars and Transfers APIs

---

README.rst
amadeus/namespaces/_shopping.py
amadeus/shopping/__init__.py
amadeus/shopping/_transfer_offers.py
docs/index.rst
specs/namespaces/test_namespaces.py

Rename to transfer_offers instead of transfer_offers_search

Rename transfer offers method
